name: comment-pull-request

on: pull_request

jobs:
  # This is currently adding a new comment for every new event to the PR. Needs to delete a pre-existing comment first.
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add new comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.number }}
          body: |
            :fire: This is a test comment created by a pull_request event
